apiVersion: v1
description: Automated rule-based alerting for Elasticsearch
name: elastalert2
version: 2.0.5
appVersion: 2.0.5
home: https://github.com/jertel/elastalert2
sources:
- https://github.com/jertel/elastalert2
maintainers:
  - name: jertel
    email: jertel@codesim.com
engine: gotpl
